export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const RESET_CART = "RESET_CART";
export const ADD_TO_EMAIL = "ADD_TO_EMAIL";
export const HANDLE_DRAWER_VISIBILITY="HANDLE_DRAWER_VISIBILITY"
export const HANDLE_LOGIN_VISIBILITY="HANDLE_LOGIN_VISIBILITY"